### PR TITLE
Issue 510

### PR DESCRIPTION
**Pull request by koheiw**
`qutd_cpp_tokens_recompile()` is isolated be merged onto master.

### CODE REVIEW

**Comment by koheiw** [comment]
I see `1. Failure: as.corpus.corpuszip works (@test-corpus-compress.R#13) ` and package installation errors in the log, but C++ recompiler should be fine.

**Comment by koheiw** [comment]
Worth restarting Travis.

**Comment by kbenoit** [comment]
@koheiw this looks fine now, so merge it into master when you are ready. Might be worth adding tests for the exceptions you addressed in 93c314d and a0a5eeb

**Comment by koheiw** [comment]
I added some tests of robustness. If this commit passes the test, all done.

**Pull request merged**
