### PR TITLE
Issue 882

### PR DESCRIPTION
**Pull request by koheiw**

### CODE REVIEW

**Comment by koheiw** [comment]
We can use ngram and skip arguments in `dfm.tokens` now. I think `tokens.tokens` should have the same signature as `dfm.tokens` (It is more like `tokens.characters` currently).

**Comment by kbenoit** [comment]
I'm  not sure what you mean by `tokens.tokens` having the `dfm.tokens` signature.

**Comment by koheiw** [comment]
I don't know why I said "tokens.tokens should have the same signature as dfm.tokens", but it is out my concern regarding different outputs from `tokens.tokens` and `tokens.chars` as shown below. 
```r
txt = "abc be-fg hi 100kg 2017"
tokens(tokens(txt, remove_hyphens = FALSE), remove_hyphens = TRUE)
# [1] "abc"   "be fg" "hi"    "100kg" "2017"

tokens(txt, remove_hyphens = TRUE)
# [1] "abc"   "be"    "-"     "fg"    "hi"    "100kg" "2017"


tokens(tokens(txt, remove_hyphens = FALSE), remove_hyphens = TRUE, ngrams = 2)
# [1] "abc_be"     "be_-"       "-_fg"       "fg_hi"      "hi_100kg"   "100kg_2017"

tokens(txt, remove_hyphens = TRUE, ngrams = 2)
# [1] "abc"   "be"    "-"     "fg"    "hi"    "100kg" "2017"

```
Tokenization is irreversible transformation from texts to tokens, but `tokens.tokens` gives an impression that we can redo tokenenization after the first tokenization. I think it is better to keep it only internal and use only in `dfm.tokens` to trap extra arguments (`ngrams` and `dictionary`).

**Comment by kbenoit** [comment]
I see the point - you cannot restore something by setting `tokens(x, remove_something = FALSE)` if the `x` was already created by `tokens(x, remove_something = TRUE)`. 

When we implement the settings functionality (described in #536 and #63) we will be able to check this and issue warnings. I don't think many people will be using `tokens.tokens()` anyway, but let's leave it exposed and I will add a caution note to the documentation.

**Pull request merged**
