### PR TITLE
Fix tests for textfile.R

### PR DESCRIPTION
**Pull request by adamobeng**
Re-include tests which had been commented out, fixing some, and skipping them on Windows or CRAN as appropriate.

### CODE REVIEW

**Comment by kbenoit** [comment]
Does this fit within the size limits?

**Comment by adamobeng** [comment]
Technically, yes, and the travis build isn't complaining about the installed size. But we should probably still remove the encoding test files. I don't think there's a way to exclude them from the package and still use them for tests. Should I try to generate them on the fly while the tests are being run?

**Comment by kbenoit** [comment]
Can we not use the encodedTextFiles object that I added in April? It was designed for the same purpose.

Sent from my iPhone

On 21 Jun 2016, at 17:22, Adam Obeng <notifications@github.com<mailto:notifications@github.com>> wrote:


Technically, yes, and the travis build isn't complaining about the installed size. But we should probably still remove the encoding test files. I don't think there's a way to exclude them from the package and still use them for tests. Should I try to generate them on the fly while the tests are being run?

-

**Comment by adamobeng** [comment]
Not really, because

- it doesn't cover many of the encoding possibilities we might support
- encodedTextFiles doesn't have a representation of the correct decodings of the input files

**Comment by adamobeng** [comment]
@kbenoit This branch now still runs the encoding tests locally (but not on travis or CRAN), and doesn't include the encoding test files in the built package (total archive size is 4.1MiB).

**Comment by kbenoit** [comment]
Not passing the CHECK on my system:

```r
* checking tests ...
  Running ‘testthat.R’ ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  
  
  testthat results ================================================================
  OK: 881 SKIPPED: 0 FAILED: 6
  1. Failure: test globbed tar file (@testTextfile.R#178) 
  2. Failure: test json files (@testTextfile.R#308) 
  3. Error: test encoding handling (skipped on travis and CRAN (@testTextfile.R#485) 
  4. Failure: A single-level tar file containing txt files can be loaded (@testTextfile.R#543) 
  5. Failure: A single-level tar.gz file containing txt files can be loaded (@testTextfile.R#551) 
  6. Failure: A single-level tar.bz file containing txt files can be loaded (@testTextfile.R#560) 
  
  Error: testthat unit tests failed
  Execution halted
 [8s/33s]
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... OK
* DONE
Status: 1 ERROR

See
  ‘/Users/kbenoit/Dropbox/GitHub/quanteda.Rcheck/00check.log’
for details.

checking tests ... ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  
  
  testthat results ================================================================
  OK: 881 SKIPPED: 0 FAILED: 6
  1. Failure: test globbed tar file (@testTextfile.R#178) 
  2. Failure: test json files (@testTextfile.R#308) 
  3. Error: test encoding handling (skipped on travis and CRAN (@testTextfile.R#485) 
  4. Failure: A single-level tar file containing txt files can be loaded (@testTextfile.R#543) 
  5. Failure: A single-level tar.gz file containing txt files can be loaded (@testTextfile.R#551) 
  6. Failure: A single-level tar.bz file containing txt files can be loaded (@testTextfile.R#560) 
  
  Error: testthat unit tests failed
  Execution halted
R CMD check results
1 error  | 0 warnings | 0 notes

R CMD check succeeded
```

**Pull request merged**
