### PR TITLE
Issue 657

### PR DESCRIPTION
**Pull request by koheiw**
For #619 #657. This should be much faster and consistent than old one as many operations are vectorized.

### CODE REVIEW

**Comment by koheiw** [comment]
With 138K documents, 
```r
Old:
   user  system elapsed 
 83.104   0.000  83.124 

New:
   user  system elapsed 
 34.912   0.212  35.203
```

**Comment by kbenoit** [comment]
Very nice. I like the streamlined code and the efficiency gain. Two comments:

1.  The addition of the `docid` docvar for `corpus_segment()` takes this one step closer to `corpus_reshape()`, with the main difference of `corpus_reshape` of course being that it can be returned to its original shape. This points to several options to differentiate or collapse them:
    a. We merge the functions and eliminate one of them.
    b. We remove `docid` from `corpus_segment()`, or at least make it `_docid` to hide it.
    c. We leave it as it is now.

2.  The elimination of the ability to set the `delimiter` when `what = "paragraphs"` limits the user's options while focusing on the definition of a paragraph. Obviously the `what = "other"` offers complete flexibility around this, but that may not be obvious to all users.

    Here's an idea: We add a new option `quanteda_paragraph_delimiter = "(\\r{0,1}\\n{1}){2}"` that sets the number of newlines expected to 2, but this can be redefined to 1 as an option. We could just make this an integer, and define the newlines internally. I like the idea of trying to capture the differences in antique Windows newlines, versus Unix-style. I also recall however that antique Mac was just "\r". What if we normalise this in the corpus upon corpus creation?

    ```r
    stringi::stri_split_regex("line1\r\n\r\nline2\n\nline3", "(\\r{0,1}\\n{1}){2}", 
                              omit_empty = TRUE)
    ## [[1]]
    ## [1] "line1" "line2" "line3"
    ```

    but that still does not get antique Mac formats.

**Comment by koheiw** [comment]
@kbenoit , thank you for reviewing and commenting. I made several changes:

- EOL normalization is done i when `corpus` is created (\r\n and \r are all converted to \n)
- corpus_segment accepts `delimiter` when `what = paragraphs`
- corpus_segment records document ID and segment ID in internal docvars (_docid and _segid).

Rearding the `quanteda_paragraph_delimiter` option, it is always good to centralize project level settings options, but EOL markers differ document to document (e.g. Bush 2005 in `data_corpus_inaugural`). I also don't think users who do not understand regex can correctly set the number of \n for paragraph endings, in the first place.

Having added `segid`, `corpus_segment` is one more step closer to `corpus_reshape`. If we are to keep `corpus_reshape` I can easily rewrite the function using `corpus_segment` internally for sentences and paragraphs, but not sure what to do with tags. I can still reconstruct tagged texts nearly completely, it does not look like 'reshaping'. Also, I think users should not transform corpus back and forth as conversion potentially destroy the data.

**Comment by koheiw** [comment]
Travis got stuck.

**Pull request merged**
