### PR TITLE
Implement new phrase behaviour for tokens_compound (#837)

### PR DESCRIPTION
**Pull request by koheiw**
This PR passed the new test in #837, but failed in old tests. I am not going to edit old tests.

### CODE REVIEW

**Comment by koheiw** [comment]
That is a test for tokens-like object attached to sequences objects, but we no longer using those, so we can remove the test. 

It is mysterious that it does not work on you Mac (my Windows and Linux are OK). Please check what types the output objects have.

**Comment by kbenoit** [comment]
Very mysterious... I checked it on my Windows 10 VM (where I have installed R 4.1 already) and the tests passed. But on my macOS 10.12.5 it still produces the old behaviour. I've tried it on my second Mac - same result. I've tried Clean & Rebuild, and installing the `issue-837` branch via `devtools::install_github`, and its all the same result.

```r
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] testthat_1.0.2

loaded via a namespace (and not attached):
[1] compiler_3.4.0  magrittr_1.5    R6_2.2.2        Matrix_1.2-10   tools_3.4.0     crayon_1.3.2   
[7] grid_3.4.0      lattice_0.20-35

> str(tokens_compound(tokens("a b c d"), phrase(c("a b", "a b c")), join = FALSE))
List of 1
 $ : chr [1:3] "a_b_c" "a_b" "d"
 - attr(*, "types")= chr [1:3] "d" "a_b" "a_b_c"
 - attr(*, "padding")= logi FALSE
 - attr(*, "class")= chr [1:2] "tokens" "tokenizedTexts"
 - attr(*, "what")= chr "word"
 - attr(*, "ngrams")= int 1
 - attr(*, "concatenator")= chr "_"
```

**Comment by kbenoit** [comment]
Here's another freaky result: This passes on (my) macOS (from `test-sequences_old.R`):
```r
    toks <- tokens('E E a b c E E G G f E E f f G G')
    seqs <- sequences_old(toks, "^[A-Z]$", valuetype="regex", case_insensitive = FALSE,
                      min_count = 1, nested = FALSE, ordered = FALSE)
    
    # seqs have the same types
    expect_equivalent(as.list(tokens_compound(toks, seqs, join = FALSE)),
                      list(c("E_E", "a", "b", "c", "E_E_G_G", "E_E", "G_G", "f", "E_E", "f", "f", "G_G")))
 ```
I get:
```r
tokens_compound(toks, seqs, join = FALSE)
## tokens from 1 document.
## Component 1 :
##  [1] "E_E"     "a"       "b"       "c"       "E_E_G_G" "E_E"     "G_G"     "f"       "E_E"     "f"      
## [11] "f"       "G_G" 
```

**Comment by koheiw** [comment]
Think we fixed by `dev-tbb_enabled`.

**Comment by kbenoit** [comment]
@koheiw Can you look at https://github.com/kbenoit/quanteda/issues/837#issuecomment-314383194 - what do you think?

**Comment by kbenoit** [comment]
@koheiw on Appveyor I'm seeing:
```
* checking compiled code ... NOTE
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
File 'quanteda/libs/i386/quanteda.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'
It is good practice to register native routines and to disable symbol
search.
See 'Writing portable packages' in the 'Writing R Extensions' manual.
```

**Pull request merged**
