### PR TITLE
plot function for wordfish

### PR DESCRIPTION
**Pull request by conjugateprior**
The new plot function makes both ideal point-style plots (theta plus confidence interval on the x, document labels on the y) with optional renaming and sorting, and 'eiffel tower' plots (beta on the x, psi on the y, feature names over-plotted with alpha transparency, optionally some highlighted) as the original Slapin and Proksch paper.

### CODE REVIEW

**Comment by adamobeng** [comment]
@conjugateprior thanks! We try to issue pull requests from feature branches so that the PR can be modified without having to be re-created. I've moved this to [PR 233](https://github.com/kbenoit/quanteda/pull/233), and tweaked it so the CI checks pass.

**Comment by conjugateprior** [comment]
I'm happy to run with whatever contributor conventions you're working with,
but I have to know what they are. Here, I'm not quite sure what would be
preferred. I branched and made a PR. What is bit of structure was missing
from that process? You'd prefer I used an existing branch? Is there maybe a
write-up for contributors someplace?

**Comment by kbenoit** [comment]
You did exactly the right thing, but @adamobeng had already been working on a parallel branch that implemented a plot method for scaled estimates from different code. I think he has now merged the two branches, but I have notes and will review the branches asap (a few days however). 

Adam had his last day at LSE today before returning to Columbia so we spent the last 48 hours tidying up branches, PRs, loose ends, etc.

**Comment by conjugateprior** [comment]
Oh noes! No more @adamobeng (at least for you - I guess he's just up the road for me...)

**Comment by conjugateprior** [comment]
Also thanks for clarifying.  As you know, I've done a lot of open source development but I've never had one soul ask to help help on the code, so this code collaboration business is kind of new to me...

**Pull request closed without merging**
