### PR TITLE
Dev kwic2

### PR DESCRIPTION
**Pull request by koheiw**
Just to check with Appveyor.

### CODE REVIEW

**Comment by kbenoit** [comment]
@koheiw did you branch this from master, or from `dev_kwic`? If from `master`, then it's not a solution to the broken `dev_kwic`...

**Comment by koheiw** [comment]
Is the new kwic in the master?

**Comment by kbenoit** [comment]
No - we are trying to fix `dev_kwic` first so that we can push it to `master`. 

How about you add to `dev_kwic` whatever fixes are now in `dev_kwic2`. Of course make sure you fetch the latest changes to `dev_kwic2` first.

**Comment by koheiw** [comment]
I am only messing with dev_kwic2 to identify the cause now. Fix will be added to dev_kwic.

**Pull request closed without merging**
