### PR TITLE
Add textplot_frequency and textplot_topfeatures

### PR DESCRIPTION
**Pull request by kbenoit**
Replaces #828, since because your PR was from your copy of the `master` branch, I could not modify it. So I copied the branch, modified it, and issued this PR.

@stefan-mueller I'd like to see the following further changes:

- [x] `features` can be a vector, should this be allowed, or should a warning or error be issued?  Maybe multi-panes as with `textplot_xray()`?
- [x] check that `doclabels` are same length as `ndoc(x)`
- [x] label the x-asix with the weight type (`"type"`)
- [x] add tests (see `test-plots.R`)

### CODE REVIEW

**Comment by kbenoit** [comment]
@koheiw I've reviewed this very thoroughly now, made a few more tweaks, and looked at exactly the tests that are not passing still. 

1. An issue with nested compounds. This is (mainly) what is causing `test-sequences.R` (and `test-sequences_old.R`) to fail. I added a new text to `test-tokens_compound.R` as well:

```r
    expect_equal(
        as.character(tokens_compound(tokens("a b c d"), phrase(c("a b", "a b c")))),
        c("a_b_d", "d")
    )
```

2. The new `kwic()` behaviours are not yet implemented.

**Comment by stefan-mueller** [comment]
Thanks for having a look and the suggestions, @kbenoit. I hope I could solve three of the four problems (check doclabels, add tests, change x-axis and ggtitle) with the two commits. 

The multi-panes option is still missing – what is the best way to get a data frame that has the following structure?

```r
texplot_frequency(mydfm, feature = c("america", "congress"))

# 'feature_data_frame' in textplot_frequency.dfm() should look like this:
  doclabels  feature freq
1      doc1  america    1
2      doc2  america    3
3      doc1 congress    4
4      doc2 congress    2
```

I thought about a loop that counts the frequency of each `feature` in the vector for each document, but I am sure there is a faster option. When we have the data frame in the long format above, we can use `facet_grid` to plot multi-panes.

**Comment by kbenoit** [comment]
Loops?? 😱 

```r

mydfm <- dfm(data_corpus_irishbudget2010)
feature = c("tax", "ireland")
freqs <- mydfm[1:3, feature]  # for illustration, just use 1st 3 docs
freqs
Document-feature matrix of: 3 documents, 2 features (0% sparse).
# 3 x 2 sparse Matrix of class "dfmSparse"
#                                   features
# docs                               tax ireland
#   2010_BUDGET_01_Brian_Lenihan_FF   38      15
#   2010_BUDGET_02_Richard_Bruton_FG   4       5
#   2010_BUDGET_03_Joan_Burton_LAB    27      13

data.frame(doclabels = rep(docnames(freqs), ncol(freqs)),
           feature = rep(featnames(freqs), each = ndoc(freqs)),
           freq = as.vector(freqs))
#                          doclabels feature freq
# 1  2010_BUDGET_01_Brian_Lenihan_FF     tax   38
# 2 2010_BUDGET_02_Richard_Bruton_FG     tax    4
# 3   2010_BUDGET_03_Joan_Burton_LAB     tax   27
# 4  2010_BUDGET_01_Brian_Lenihan_FF ireland   15
# 5 2010_BUDGET_02_Richard_Bruton_FG ireland    5
# 6   2010_BUDGET_03_Joan_Burton_LAB ireland   13
```

**Comment by stefan-mueller** [comment]
Ok, I implemented multi-faceting and updated the tests. I guess Travis fails because of the problems you mention above (`test_sequences.R` and `test-sequences_old.R`)? If there are problems with the code in `textplot_frequency.R`, `texplot_topfeatures.R` or `test-plots.R`, let me know.

**Comment by stefan-mueller** [comment]
I'm wondering whether we could/should merge this to the master or whether we need to do anything else. Once `topfeatures()` can be calculated by document/group, we could add this option; other than that, the plots (hopefully) should be fine?

**Comment by kbenoit** [comment]
@stefan-mueller I've been delaying merging since I wanted to think more about and discuss how to integrate the two plotting functions, since I think they are doing very similar things that could be distinguished by an option. Also I wanted to complete the `textstat_keyness()` work since I see that as a more consistent model for this function too: first adding a `textstat_frequency()` function and then defining the plot method `textplot_frequency()` to work on the results of that object. 

Happy to discuss.

**Comment by stefan-mueller** [comment]
That makes sense. Waiting for `textstat_frequency()` seems very reasonable. Once this has been done, we can continue here. Let me know when you are ready and I'm happy to discuss possible changes and improvements.

**Pull request closed without merging**
