### PR TITLE
Added Yates correction and min_count to testplot_keyness

### LINKED ISSUE #785: Feature suggestion: mutual information measure and keyness plot
Hi,

I'd like to suggest adding a mutual information measure to quanteda. This could just be another measure that users are able to choose in ```textstat_keyness```. In addition, it would also be awesome to have a plot for keyness term comparisons which could look similar to this one (from [Grimmer 2010](http://web.stanford.edu/~jgrimmer/ExpAgendaFinal.pdf)):

image

### PR DESCRIPTION
**Pull request by HaiyanLW**
fix  #785

### CODE REVIEW

**Comment by kbenoit** [comment]
Sorry for the extra work, but I think it made more sense before either to simply automatically apply Yates (and Williams) for Chi2 (and G2), or to provide the option for correction TRUE or FALSE.

**Comment by HaiyanLW** [comment]
Currently, we offer option for user to set the value of correction, and the default is Yates (`0.5`); and for each word the correction is applied only if its smallest expected frequency is less than `5` -- which means that the correction may still not be applied to each word. Since there's an argument about whether `Yates` over-corrects, user can choose not applying correction by set it to `0` or a smaller number. 
So you prefer to provide the option for `correction = TRUE` instead of a free value setting? And if so, do we still check the smallest expected frequency? 
And for `pmi`?

**Comment by kbenoit** [comment]
how about:

```r
correction = c("default", "yates", "williams", "none")
```
where we explain in the details that "default" is yates for chi2, williams for lr, and none for pmi?

These options allow the user to override. So the main change you would need to is change this from being numeric to being (back to) the character label, and to set the conditions. And to check whether williams for chi2 makes any sense. I don't think yates or williams for pmi is applicable.

**Comment by HaiyanLW** [comment]
Agree. 
Didn't find any reference of corrections for `pmi`, though we could add `normalised pmi` in `measure`.

**Comment by kbenoit** [comment]
normalised as in `tf(x, "prop")`? Sounds reasonable.

**Comment by HaiyanLW** [comment]
As `npmi≡pmi/(−logp(x,y))`, so pmi is normalized between [-1,1]

**Comment by HaiyanLW** [comment]
William's works for `chi2` as well, see http://www.biostathandbook.com/small.html

**Comment by kbenoit** [comment]
even better

**Pull request merged**
