### PR TITLE
solve #564 implement sparse ca

### PR DESCRIPTION
**Pull request by HaiyanLW**

### CODE REVIEW

**Comment by HaiyanLW** [comment]
Wait, don't pull yet. :)

**Comment by kbenoit** [comment]
OK - I was going to say it all looks fantastic. Two questions:

1. Do we need RSpectra as an option too? would not rsvd be sufficient?
2. The option `mt` and `threads` are different from how we implement this in wordfish, where it's `sparse` and `threads`. In text model_ca, what happens when `mt = TRUE, threads = 2`?

**Comment by HaiyanLW** [comment]
RSpectra is based on an established method "ARPACK", which is also used in `matlab` etc.

**Comment by HaiyanLW** [comment]
Removed the `method` option.
Still kept the `sparse = FALSE` and `threads = 1` so that when `sparse = TRUE` and `threads = 1` to retain the sparsity and keep the memory cost low.

**Comment by kbenoit** [comment]
Ok so it's like textmodel_worfish now.

**Pull request merged**
