### PR TITLE
Issue 434

### PR DESCRIPTION
**Pull request by koheiw**
This branch contains a prototype for `textstat_collocations` resuscitated from `dev-collocations`.

### CODE REVIEW

**Comment by kbenoit** [comment]
Outstanding. I've restarted Travis and will accept the PR when it's done.

We can discuss the segment v reshape next week, will keep as is for next release. I currently use the reshape for instance to go from docs to sentences, trimming some sentences or resampling them, and then reshaping back to documents. (This is how `bootstrap_dfm()` works for instance, or `corpus_trimsentences()`.)

**Comment by koheiw** [comment]
I agree that it is good to have tools for corpus cleaning/pre-processing, but dfm_bootstamp should reconstruct in `dfm` with `group = _docid`.

**Comment by kbenoit** [comment]
Need to define as.tokens method:

```r
> txts <- c("This is software testing: looking for (word) pairs!  
+            This [is] a software testing again. For.",
+           "Here: this is more Software Testing, looking again for word pairs.")
> toks <- tokens(txts)
> cols <- textstat_collocations(toks, method = "lr", "^([a-z]+)$", 
+                                valuetype = "regex", min_count = 1)
> as.tokens(cols)
Error in UseMethod("as.tokens") : 
  no applicable method for 'as.tokens' applied to an object of class "c('collocations', 'data.frame')"
```

**Comment by kbenoit** [comment]
Also I think it would be better to have the collocations not as row names but as a column in the data.frame. We want collocations to become one of the "sequences" and "features" types for items like `tokens_compound()` or `kwic()`, in addition to the existing sequences.

**Comment by kbenoit** [comment]
Finally I like the output of the `sequences` data.frame, we should coerce the other methods to produce the same sort of output.

**Comment by koheiw** [comment]
`as.tokens` is in collocations2.R, but commented out now.

**Comment by koheiw** [comment]
I changed the outputs of `textstat_collocations()` (and its underlying functions) to record collocations in a column 'collocation' instead of row names. Collocation objects' `[]` and `as.tokens()` methods are activated and attributes are renamed. 

There are conflicts between old and new objects, leading to the errors in the tests. We have to remove the old collocation objects as well as examples and tests in `removeFeatures` to solve this.

I am happy with the current implementation and usability of `textstat_collocations`. I am reluctant to remove `features` argument at this stage, because it then requires a big change in `tokens_select()` that affects every bit of the package.

**Comment by koheiw** [comment]
AppVayor is failing only because the XML and yaml packages aren't available.

**Comment by kbenoit** [comment]
Ok just landed. Will review later this afternoon. Might call you.

**Comment by kbenoit** [comment]
@koheiw I think this is a bug in `as.tokens.collocations()` or in the `types` attr that is set in the collocations.

```r
txts <- c("quanteda is a package for quantitative text analysis.",
          "Quantitative text analysis is a rapidly growing field.",
          "The population is rapidly growing.")
toks <- tokens(txts)

(cols <- textstat_collocations(toks, method = "lr", max_size = 3, min_count = 2))
#       collocation count        G2
# 1   text analysis     2 13.208672
# 2 rapidly growing     2 13.208672
# 3            is a     2  9.389587

as.tokens(cols)
# tokens from 36 documents.
# Component 1 :
#     [1] "text"     "analysis"
# 
# Component 2 :
#     [1] "rapidly" "growing"
# 
# Component 3 :
#     [1] "is" "a" 
# 
# Component 4 :
#     [1] "package" "for"    
# 
# Component 5 :
#     [1] "for"          "quantitative"
# 
# Component 6 :
#     [1] "The"        "population"
# 
# Component 7 :
#     [1] "a"       "package"

...etc
```

**Comment by kbenoit** [comment]
Also, I'm not clear how the `case_insensitive` is supposed to operate here. Should it not count "quantitative text analysis" twice if `case_insensitive = TRUE`? (But then what is the "collocation" that gets returned: the upper or lowercase version?)

```r
txts <- c("quanteda is a package for quantitative text analysis.", 
           "Quantitative text analysis is a rapidly growing field.", 
           "The population is rapidly growing.")
toks <- tokens(txts)
textstat_collocations(toks, method = "lr", case_insensitive = FALSE)
#       collocation count        G2
# 1   text analysis     2 13.208672
# 2 rapidly growing     2 13.208672
# 3            is a     2  9.389587
textstat_collocations(toks, method = "lr", case_insensitive = TRUE)
#       collocation count        G2
# 1   text analysis     2 13.208672
# 2 rapidly growing     2 13.208672
# 3            is a     2  9.389587
```

**Comment by koheiw** [comment]
The first issues is time of setting class `collocation` that trigers `[]`. I will fix now.

**Comment by koheiw** [comment]
`case_insensitive` is only for feature selection, so tokens are counted in their original forms. This argument should be hidden along with `features` and `valuetype`.

```r
txts <- c("QUANTEDA IS A PACKAGE FOR QUANTITATIVE TEXT ANALYSIS.", 
          "QUANTITATIVE TEXT ANALYSIS IS A RAPIDLY GROWING FIELD.", 
          "THE POPULATION IS RAPIDLY GROWING.")
toks <- tokens(txts)

textstat_collocations(toks, method = "lr", case_insensitive = TRUE, max_size = 3)
                 collocation count        G2
1          QUANTITATIVE TEXT     2 13.208672
2              TEXT ANALYSIS     2 13.208672
3            RAPIDLY GROWING     2 13.208672
4                       IS A     2  9.389587
5 QUANTITATIVE TEXT ANALYSIS     2 25.115911

textstat_collocations(toks, method = "lr", case_insensitive = FALSE, max_size = 3)

                 collocation count        G2
1          QUANTITATIVE TEXT     2 13.208672
2              TEXT ANALYSIS     2 13.208672
3            RAPIDLY GROWING     2 13.208672
4                       IS A     2  9.389587
5 QUANTITATIVE TEXT ANALYSIS     2 25.115911
```

**Comment by koheiw** [comment]
Fixed
```r
> txts <- c("quanteda is a package for quantitative text analysis.",
+           "Quantitative text analysis is a rapidly growing field.",
+           "The population is rapidly growing.")
> toks <- tokens(txts)
> 
> (cols <- textstat_collocations(toks, method = "lr", max_size = 3, min_count = 2))
      collocation count        G2
1   text analysis     2 13.208672
2 rapidly growing     2 13.208672
3            is a     2  9.389587
> 
> as.tokens(cols)
tokens from 3 documents.
Component 1 :
[1] "text"     "analysis"

Component 2 :
[1] "rapidly" "growing"

Component 3 :
[1] "is" "a" 
```

**Comment by kbenoit** [comment]
On the `case_insensitive`, that's fine. If a user wants to consider case as equivalent, then the user should first lowercase the tokens.

The nesting behaviour is still inconsistent between methods, but we can put that on the to do list for the next set of revisions. 
```r
> txts <- c("quanteda is a package for quantitative text analysis", 
+           "quantitative text analysis is a rapidly growing field", 
+           "The population is rapidly growing")
> toks <- tokens(txts)
> textstat_collocations(toks, method = "bj", max_size = 3, min_count = 2, nested = TRUE)
                 collocation    lambda   sigma count         z         p
1 quantitative text analysis -4.496508 3.32119     2 -1.353884 0.9121134
> textstat_collocations(toks, method = "lr", max_size = 3, min_count = 2, nested = TRUE)
                 collocation count       G2
1          quantitative text     2 12.55796
2              text analysis     2 12.55796
3            rapidly growing     2 12.55796
4                       is a     2  8.73887
5 quantitative text analysis     2 23.56047
```
although because the `"bj"` method only returns collocations below the p-value scoring threshold, in this  short example we don't get to see the nesting behaviour in this short example.

**Pull request merged**
