### PR TITLE
tokenize() to tokens() - Fix 795

### PR DESCRIPTION
**Pull request by kbenoit**
Does not completely solve the memory issue in #795 but helps. 

* `ntoken.character()` and `ntype.character()` methods now use `tokens(x, hash = FALSE)` instead of `tokenize()`, since this is faster and since `tokenize()` is deprecated. Turning off hashing avoids the unnecessary construction of the hash table, which is not needed for these functions. (My tests showed this to be faster.)
* Changed usage in other functions from `tokenize()` to `tokens()` - in the few hidden corners where this was still used.
* Fixed a bug in the corpuszip constructor that overwrote the `created` field in metacorpus data, even when this had been set previously by the user.

### CODE REVIEW

**Comment by kbenoit** [comment]
But the intermediate object inside  `tokens()` is the unhashed, segmented words, before we hash it, so here we are not changing that, but simply avoiding the additional time required to hash the tokens.

**Comment by koheiw** [comment]
In #795, 306,108 documents will be split into 31 blocks, and serialized one by one. So the intermediate object is much smaller than unserialized tokens.

**Comment by kbenoit** [comment]
@koheiw you are right about the loop. I changed it back to the default, removing the `hash = FALSE` in the `tokens()` calls.

Once the corpus is an index of tokens this will become irrelevant and we will not need to compute this in the same way again, since we will be able to take this directly from querying subsets of the tokenised corpus.

**Comment by koheiw** [comment]
This is the difference:

The data is only the half, but `tokens` uses 1.3GB when `hash = TRUE`, and 3.5GB while `hash = FALSE`.
```r
> load("/home/kohei/Documents/Brexit/Analysis/data_corpus_guardian.RData")
> ndoc(data_corpus_guardian)
[1] 177115

> gc(reset = TRUE) 
            used   (Mb) gc trigger   (Mb)  max used   (Mb)
Ncells   2762817  147.6    4703850  251.3   2762817  147.6
Vcells 173160717 1321.2  323266785 2466.4 173160717 1321.2
> out <- tokens(data_corpus_guardian, hash = FALSE)
 Show Traceback
 
 Rerun with Debug
 Error in UseMethod("docvars<-") : 
  no applicable method for 'docvars<-' applied to an object of class "c('tokenizedTexts', 'list')" > gc()
            used   (Mb) gc trigger   (Mb)  max used   (Mb)
Ncells   3008426  160.7    4703850  251.3   4647974  248.3
Vcells 178317679 1360.5  465680170 3552.9 465680096 3552.9
```
I can see `dovars` error, but let's ignore this as we defunction tokenizedTexts soon.

**Pull request merged**
