### PR TITLE
Dev contexts

### PR DESCRIPTION
**Pull request by koheiw**
I added `remove_keywords` and `overlap`. If you have an idea how a new `kwic.print()` will look like, it is great to see that first, so that I can make changes in the C++ code.

### CODE REVIEW

**Comment by kbenoit** [comment]
I think the new kwic print should look just like the old. Otherwise it's not really a kwic in the convention of aligned words that is almost universally used.

If there are multiple target words within a context, could we split them for the printing? maybe write a function to split these? in case someone wanted to convert?

**Comment by kbenoit** [comment]
And I really like the new formatting of the print.kwic method that you redid some months ago, it's much neater-looking than the previous one that I had done. Don't mess with a winning format.

**Comment by koheiw** [comment]
The functions splits contexts with multiple keywords when `overlap=TRUE`. I like the current look too, but we are dependent on R's column alignment for `data.frame`. As far as we use `data.frame`, we cannot get rid of the nested loops around `kwic_split()`, which is really inefficient.

**Comment by kbenoit** [comment]
Actually I take back what I said earlier, having thought about it a bit. Let's keep kwic as is, where the overlaps are split as they are in current kwic, always. To get the multiple target words in one context, as you want, we write the function to "unsplit" the lines. This can be done easily and quickly by checking the overlap of the index positions +/- the context width. So a kwic is always the same structure of object, but if you want to combine lines, a separate function will do that when and if as needed.

**Comment by koheiw** [comment]
I do not think undo things is easy. It simply look like `kwic` and `contexts` are too different to integrate. This was my earlier conclusion.

**Comment by kbenoit** [comment]
I think it would be very straightforward to redefine the kwic object to be like the contexts object when overlap = [whatever splits the lines and only has a single target word]. That offers every advantage of contexts except the ability to have overlap = ![what I said above], and gains the efficiencies of keeping the hashes rather than the text.

But the structure of the kwic needs to have the same essential format, which is a key word or pattern (singular) surrounded by context.

Wanting multiple key words in overlapping context is a special case that few users want, we write a method to use the index positions to paste together those lines if you want them that way. I also suggest a function to replace the key words with pads if that is wanted. 

Then we end up with
a) more efficient kiwc
b) the ability to get the fro that the "contexts" objects that you wanted for other uses

But I don't want to have both kwic and contexts in the package since they are two functions to perform slight variations of the same action.

**Comment by koheiw** [comment]
Before discussing integrating kwic and contexts, we have to find a way to speed up kwic in the R side. 20x slow down is coming from the double loop in R to create character strings for pre and post contexts.
```
toks <- tokens(data_char_inaugural)
microbenchmark::microbenchmark(
     kwic(toks, "the", window = 3, valuetype = "fixed"),
     kwic_cpp(toks, "the", window = 3, valuetype = "fixed"))
Unit: milliseconds
                                                   expr       min        lq      mean    median        uq       max neval
     kwic(toks, "the", window = 3, valuetype = "fixed") 611.44780 697.97627 868.90236 797.92416 997.27889 1574.0114   100
 kwic_cpp(toks, "the", window = 3, valuetype = "fixed")  28.06211  33.20447  39.67117  35.58465  41.68219  115.4242   100
```

**Comment by koheiw** [comment]
The decision whether separating `contexts` apparently depends on how useful it is. When I am trying to find synonyms of 'alliance' (同盟) in Japaneses news corpus, I found that LSA works better on contexts than on sentences better and quicker. The top words in the first table is more strongly related to 'alliance' in the context of diplomacy. This means that the contexts can useful for word embedding models. It is no surprise actually, because that the Mikolov et al. takes similar approach with sikipgrams. `contexts`  should not be undersold!

```r
# contexts
                   en       ja     score
1            alliance     同盟 1.0000000
2        coordination     協調 0.4063619
3               close     緊密 0.3811295
4               since     以来 0.3674668
5             partner     相手 0.3536051
6         cooperation     連携 0.3524309
7           bilateral   二国間 0.3510237
8          Republican   共和党 0.3054374
9               depth       深 0.2801993
10 friendly relations 友好関係 0.2759720
11   China and Russia     中ロ 0.2747523
12               home     本国 0.2702761
13               axis       軸 0.2677267
14               flag       旗 0.2676331
15  Japan-US alliance 日米同盟 0.2658351
16  military alliance 軍事同盟 0.2593082
17              build     構築 0.2579929
18         pivot foot     軸足 0.2525127
19              enemy       敵 0.2440766
20             strong     強固 0.2430750

# sentences
                               en           ja     score
1                        alliance         同盟 1.0000000
2                        district         地区 0.4772546
3                     chairperson       委員長 0.4466363
4                           north         北部 0.3739494
5                        standing           在 0.2856792
6  Japan-US security arrangements 日米安保体制 0.2661019
7                      Department         専攻 0.2567505
8                        alliance     同盟関係 0.2486264
9                         defense         国防 0.2345750
10                            led         筆頭 0.2320058
11                      Committee           委 0.2248981
12                    maintenance         保守 0.2165109
13                Communist Party       共産党 0.2066653
14                      principle         原則 0.2059490
15           military cooperation     軍事協力 0.2014359
16        national defense policy     国防政策 0.1987170
17              US-Japan alliance     日米同盟 0.1948226
18                        Liberal     リベラル 0.1941108
19                           axis           軸 0.1901899
20                      bilateral       二国間 0.1885830


```

**Comment by kbenoit** [comment]
Something broken here:

```r
> example(kwic)

kwic> head(kwic(data_char_inaugural, "secure*", window = 3, valuetype = "glob"))

 Error in qatd_cpp_kwic(x, types, keywords_id, window) : vector 

> kwic(data_corpus_inaugural, "american")
 Error in qatd_cpp_kwic(x, types, keywords_id, window) : vector 
```

**Comment by kbenoit** [comment]
Also is `new = FALSE` now disabled? This make comparing harder.

**Comment by koheiw** [comment]
I do not see the error on my system.
```r
>example(kwic)
kwic> head(kwic(data_char_inaugural, "secure*", window = 3, valuetype = "glob"))
                                                                          
[1797-Adams, 479:479]        welfare, and | secure  | the blessings of    
[1797-Adams, 1517:1517]      nations, and | secured | immortal glory with 
[1805-Jefferson, 2368:2368]   , and shall | secure  | to you the          
[1817-Monroe, 1765:1765]    cherished. To | secure  | us against these    
[1817-Monroe, 1825:1825]    defense as to | secure  | our cities and      
[1817-Monroe, 3026:3026]         I can to | secure  | economy and fidelity

kwic> head(kwic(data_char_inaugural, "secur", window = 3, valuetype = "regex"))
                                                                                  
[1789-Washington, 1499:1499] government for the | security | of their union       
[1797-Adams, 479:479]              welfare, and |  secure  | the blessings of     
[1797-Adams, 1517:1517]            nations, and | secured  | immortal glory with  
[1805-Jefferson, 2368:2368]         , and shall |  secure  | to you the           
[1813-Madison, 321:321]            seas and the | security | of an important      
[1817-Monroe, 1620:1620]          may form some | security | against these dangers

kwic> head(kwic(data_char_inaugural, "security", window = 3, valuetype = "fixed"))
                                                                                    
[1789-Washington, 1499:1499] government for the | security | of their union         
[1813-Madison, 321:321]            seas and the | security | of an important        
[1817-Monroe, 1620:1620]          may form some | security | against these dangers  
[1817-Monroe, 3444:3444]               and as a | security | against foreign dangers
[1825-Adams, 1373:1373]           that the best | security | for the beneficence    
[1825-Adams, 1445:1445]        that the firmest | security | of peace is            

kwic> ## Not run: 
kwic> ##D toks <- tokens(data_char_inaugural)
kwic> ##D microbenchmark::microbenchmark(
kwic> ##D    kwic(toks, "the", window = 3, valuetype = "fixed"),
kwic> ##D    kwic(toks, "the", window = 3, valuetype = "fixed"))
kwic> ## End(Not run)
kwic> kwic(data_corpus_inaugural, "war against")
                                                                                                         
[1857-Buchanan, 2933:2934]  advantage of the fortune of | war against | a sister republic, we            
[1901-McKinley, 2284:2285]          . We are not waging | war against | the inhabitants of the Philippine
[1901-McKinley, 2299:2300]   portion of them are making | war against | the United States. By            
[1901-McKinley, 2413:2414]     used when those who make | war against | us shall make it no              
[1933-Roosevelt, 1851:1852]   Executive power to wage a | war against | the emergency, as great          

kwic> kwic(data_corpus_inaugural, "war against", valuetype = "regex")
                                                                                                                             
[1801-Jefferson, 1277:1278] domestic concerns and the surest | bulwarks against | antirepublican tendencies; the preservation
[1845-Polk, 692:693]        domestic concerns and the surest | bulwark against  | antirepublican tendencies," and            
[1857-Buchanan, 2933:2934]       advantage of the fortune of |   war against    | a sister republic, we                      
[1901-McKinley, 2284:2285]               . We are not waging |   war against    | the inhabitants of the Philippine          
[1901-McKinley, 2299:2300]        portion of them are making |   war against    | the United States. By                      
[1901-McKinley, 2413:2414]          used when those who make |   war against    | us shall make it no                        
[1933-Roosevelt, 1851:1852]        Executive power to wage a |   war against    | the emergency, as great                    
[1977-Carter, 927:928]                 and we will fight our |   wars against   | poverty, ignorance, and                    

kwic> mykwic <- kwic(data_corpus_inaugural, "provident*")

kwic> is.kwic(mykwic)
[1] TRUE

kwic> is.kwic("Not a kwic")
[1] FALSE
```

**Comment by kbenoit** [comment]
Build fails on my MacBook, on the vignette, which has the call above.

```r
Updating vignettes
Rebuilding LitVignette.Rmd

 *** caught segfault ***
address 0x1151e5ffc, cause 'memory not mapped'

Traceback:
 1: .Call("quanteda_qatd_cpp_kwic", PACKAGE = "quanteda", texts_,     types_, words_, window)
 2: qatd_cpp_kwic(x, types, keywords_id, window)
 3: kwic.tokens(tokens(x, ...), keywords, window, valuetype, case_insensitive,     new = TRUE)
 4: kwic(tokens(x, ...), keywords, window, valuetype, case_insensitive,     new = TRUE)
 5: kwic.character(novel.lower.v, "whale*")
 6: kwic(novel.lower.v, "whale*")
 7: nrow(kwic(novel.lower.v, "whale*"))
 8: eval(expr, envir, enclos)
 9: eval(expr, envir, enclos)
10: withVisible(eval(expr, envir, enclos))
11: withCallingHandlers(withVisible(eval(expr, envir, enclos)), warning = wHandler,     error = eHandler, message = mHandler)
12: handle(ev <- withCallingHandlers(withVisible(eval(expr, envir,     enclos)), warning = wHandler, error = eHandler, message = mHandler))
13: timing_fn(handle(ev <- withCallingHandlers(withVisible(eval(expr,     envir, enclos)), warning = wHandler, error = eHandler, message = mHandler)))
14: evaluate_call(expr, parsed$src[[i]], envir = envir, enclos = enclos,     debug = debug, last = i == length(out), use_try = stop_on_error !=         2L, keep_warning = keep_warning, keep_message = keep_message,     output_handler = output_handler, include_timing = include_timing)
15: evaluate(code, envir = env, new_device = FALSE, keep_warning = !isFALSE(options$warning),     keep_message = !isFALSE(options$message), stop_on_error = if (options$error &&         options$include) 0L else 2L, output_handler = knit_handlers(options$render,         options))
16: in_dir(input_dir(), evaluate(code, envir = env, new_device = FALSE,     keep_warning = !isFALSE(options$warning), keep_message = !isFALSE(options$message),     stop_on_error = if (options$error && options$include) 0L else 2L,     output_handler = knit_handlers(options$render, options)))
17: block_exec(params)
18: call_block(x)
19: process_group.block(group)
20: process_group(group)
21: withCallingHandlers(if (tangle) process_tangle(group) else process_group(group),     error = function(e) {        setwd(wd)        cat(res, sep = "\n", file = output %n% "")        message("Quitting from lines ", paste(current_lines(i),             collapse = "-"), " (", knit_concord$get("infile"),             ") ")    })
22: process_file(text, output)
23: knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet,     encoding = encoding)
24: rmarkdown::render(file, encoding = encoding, quiet = quiet, envir = globalenv())
25: vweave_rmarkdown(...)
26: engine$weave(file, quiet = quiet, encoding = encoding, ...)
27: tools::buildVignette(vign, dirname(vign), tangle = FALSE, clean = FALSE)
28: FUN(X[[i]], ...)
29: vapply(vigs$docs, vign_update, logical(1))
30: vign_update_all(base_path)
31: roclet_output.roclet_vignette(roc, results, base_path, is_first = is_first)
32: roclet_output(roc, results, base_path, is_first = is_first)
33: FUN(X[[i]], ...)
34: lapply(roclets, roc_out)
35: unlist(lapply(roclets, roc_out))
36: roxygen2::roxygenise(pkg$path, roclets = roclets, load_code = pkgload::ns_env)
37: force(code)
38: withr::with_envvar(r_env_vars(), roxygen2::roxygenise(pkg$path,     roclets = roclets, load_code = pkgload::ns_env))
39: devtools::document(roclets = c("rd", "collate", "namespace",     "vignette"))
40: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
41: suppressPackageStartupMessages({    oldLC <- Sys.getlocale(category = "LC_COLLATE")    Sys.setlocale(category = "LC_COLLATE", locale = "C")    on.exit(Sys.setlocale(category = "LC_COLLATE", locale = oldLC))    devtools::document(roclets = c("rd", "collate", "namespace",         "vignette"))})
An irrecoverable exception occurred. R is aborting now ...

Exited with status 11.
```

**Comment by koheiw** [comment]
There is not way to investigate the error unless it happens on my system...

**Comment by kbenoit** [comment]
The vignette build is failing on Travis too, although in an apparently less ugly fashion than on my MacBook.

See also the output from Appveyor where it builds, but with some errors that also need attention. Note that we cannot start removing deprecated functions (yet) e.g. `applyDictionary()` since this involves more extensive surgery. (We will perform that surgery soon though!)

**Comment by kbenoit** [comment]
Try this on your system, because it's a bug for me:

```r
toks <- tokens(c("This is a test of a sentence.", 
                 "A second sentence makes this two documents long."))
kwic(toks, "not")

 Error in qatd_cpp_kwic(x, types, keywords_id, window) : vector 
```
Same thing here:
```r
kwic(data_char_inaugural, "secur*")

 Error in qatd_cpp_kwic(x, types, keywords_id, window) : vector 
```

**Comment by koheiw** [comment]
It does not cause errors on my system, but please try it again. I fixed something.

**Comment by kbenoit** [comment]
On CHECK, I am still getting:
```
* creating vignettes ... ERROR

 *** caught segfault ***
address 0x10c934ffc, cause 'memory not mapped'

Traceback:
 1: .Call("quanteda_qatd_cpp_kwic", PACKAGE = "quanteda", texts_,     types_, words_, window)
 2: qatd_cpp_kwic(x, types, keywords_id, window)
 3: kwic.tokens(tokens(x, ...), keywords, window, valuetype, case_insensitive,     new = TRUE)
 4: kwic(tokens(x, ...), keywords, window, valuetype, case_insensitive,     new = TRUE)
 5: kwic.character(novel.v, "chapter")
 6: kwic(novel.v, "chapter")
 7: head(kwic(novel.v, "chapter"))
 8: eval(expr, envir, enclos)
 9: eval(expr, envir, enclos)
10: withVisible(eval(expr, envir, enclos))
11: withCallingHandlers(withVisible(eval(expr, envir, enclos)), warning = wHandler,     error = eHandler, message = mHandler)
12: handle(ev <- withCallingHandlers(withVisible(eval(expr, envir,     enclos)), warning = wHandler, error = eHandler, message = mHandler))
13: timing_fn(handle(ev <- withCallingHandlers(withVisible(eval(expr,     envir, enclos)), warning = wHandler, error = eHandler, message = mHandler)))
14: evaluate_call(expr, parsed$src[[i]], envir = envir, enclos = enclos,     debug = debug, last = i == length(out), use_try = stop_on_error !=         2L, keep_warning = keep_warning, keep_message = keep_message,     output_handler = output_handler, include_timing = include_timing)
15: evaluate(code, envir = env, new_device = FALSE, keep_warning = !isFALSE(options$warning),     keep_message = !isFALSE(options$message), stop_on_error = if (options$error &&         options$include) 0L else 2L, output_handler = knit_handlers(options$render,         options))
16: in_dir(input_dir(), evaluate(code, envir = env, new_device = FALSE,     keep_warning = !isFALSE(options$warning), keep_message = !isFALSE(options$message),     stop_on_error = if (options$error && options$include) 0L else 2L,     output_handler = knit_handlers(options$render, options)))
17: block_exec(params)
18: call_block(x)
19: process_group.block(group)
20: process_group(group)
21: withCallingHandlers(if (tangle) process_tangle(group) else process_group(group),     error = function(e) {        setwd(wd)        cat(res, sep = "\n", file = output %n% "")        message("Quitting from lines ", paste(current_lines(i),             collapse = "-"), " (", knit_concord$get("infile"),             ") ")    })
22: process_file(text, output)
23: knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet,     encoding = encoding)
24: rmarkdown::render(file, encoding = encoding, quiet = quiet, envir = globalenv())
25: vweave_rmarkdown(...)
26: engine$weave(file, quiet = quiet, encoding = enc)
27: doTryCatch(return(expr), name, parentenv, handler)
28: tryCatchOne(expr, names, parentenv, handlers[[1L]])
29: tryCatchList(expr, classes, parentenv, handlers)
30: tryCatch({    engine$weave(file, quiet = quiet, encoding = enc)    setwd(startdir)    find_vignette_product(name, by = "weave", engine = engine)}, error = function(e) {    stop(gettextf("processing vignette '%s' failed with diagnostics:\n%s",         file, conditionMessage(e)), domain = NA, call. = FALSE)})
31: tools::buildVignettes(dir = ".", tangle = TRUE)
An irrecoverable exception occurred. R is aborting now ...
Error: Command failed:
 '/Library/Frameworks/R.framework/Resources/bin/R' CMD build '/Users/kbenoit/Dropbox (Personal)/GitHub/quanteda' --no-resave-data --no-manual 
 sh: line 1: 92573 Segmentation fault: 11  '/Library/Frameworks/R.framework/Resources/bin/Rscript' --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)" > '/var/folders/46/zfn6gwj15d3_n6dhyy1cvwc00000gp/T//Rtmpu9qqaG/xshell1691813a7152e' 2>&1
Execution halted
```

**Comment by kbenoit** [comment]
On the tests above, it's 50% better:

```r
> toks <- tokens(c("This is a test of a sentence.", 
+                  "A second sentence makes this two documents long."))
> kwic(toks, "not")
NULL
> 
> kwic(data_char_inaugural, "secur*")

 Error in qatd_cpp_kwic(x, types, keywords_id, window) : vector 
```
but be aware of https://github.com/kbenoit/quanteda/issues/242

**Comment by koheiw** [comment]
I believe my last commit will make it another 50% better.

**Comment by kbenoit** [comment]
Almost there...  the segfault error is gone, but something is amiss with the appveyor/pr. Click on Details above and see.

**Comment by koheiw** [comment]
Yes, it makes kwic 20 times faster and adds as.tokens() method, which returns the tokens object in its attributes. This is basically the same structure as the new collocations (data.frame + tokens).

**Pull request merged**
