### PR TITLE
Dev recompile

### PR DESCRIPTION
**Pull request by koheiw**
This branch integrates tokens recompiling function into `tokens_*` functions in the C++ to cut the conversion overhead between C++ and R. This reduces the run time by around 20%.

### CODE REVIEW

**Comment by kbenoit** [comment]
Does this make any existing functions unnecessary? E.g. `reassign_attributes()`?

**Comment by kbenoit** [comment]
Also we need to do heavy duty cross-platform testing before accepting the C++ changes into master.

**Comment by koheiw** [comment]
`quanted::attributes()` does the same thing as `reassign_attributes()`, but the C++ recompiler still needs reassignmening attributes. I kept `reassign_attributes()` because I am not sure how it is used for objects other than `tokens`.

**Comment by koheiw** [comment]
There is no change in platform sensitive part like TBB or math, but I can do extra tests. What should be the cross-platform test?

**Comment by kbenoit** [comment]
Cross-platform tests would be me running this on:
* OS X El Capitan
* macOS
* Windows 10

and you could try it on:
* Solaris x86

Can we do UBSan tests using rHub?

**Comment by koheiw** [comment]
It builds successfully on my Windows 10 and rHub:
https://builder.r-hub.io/status/quanteda_0.9.9-28.tar.gz-5239ce22959c4b43afee739cb72070f8

Testing with a Solaris does not make sense, because the set up of CRAN's Solaris is not specified (my Solaris is not yet working).

**Pull request merged**
