### PR TITLE
Fix dist

### PR DESCRIPTION
**Pull request by koheiw**

### CODE REVIEW

**Comment by koheiw** [comment]
This replicates the old version, but I wonder why we return `dist` object that is not so useful. It is better to return matrix and let users to convert to the format with `stats::as.dist()`. In fact, the test always convert it back to genuine matrix with `as.matrix()`. Great that if you could merge to master soon.

**Comment by koheiw** [comment]
I am also not sure if `n` argument should be used, because it looks arbitrarily to take first n items.

**Comment by kbenoit** [comment]
OK this looks like you have removed some of the warnings that occur when using a selection argument (it complained about the non-square dist objects. But sometimes that is what we wanted, for instance with selection aimed at extracting a particular target. Below, we want the non-square result. (This allows targeted comparisons.)

```r
> presDfm <- dfm(corpus_subset(inaugCorpus, Year > 1980), 
+                remove = stopwords("english"), stem = TRUE)
> temp <- as.matrix(textstat_dist(presDfm, "1985-Reagan", n = 5, margin = "documents"))
Warning message:
In as.dist.default(result, diag = diag, upper = upper) : non-square matrix
> as.matrix(temp)
             1985-Reagan 1981-Reagan 1989-Bush 1993-Clinton 1997-Clinton
1985-Reagan      0.00000    57.68015  69.94283     89.92219     79.58643
1981-Reagan     57.68015     0.00000   0.00000      0.00000      0.00000
1989-Bush       69.94283     0.00000   0.00000      0.00000      0.00000
1993-Clinton    89.92219     0.00000   0.00000      0.00000      0.00000
1997-Clinton    79.58643     0.00000   0.00000      0.00000      0.00000
```

One way around this: We could allow the output format to be set by the user in a function argument, default is dist, but could be matrix or list. With selection, it defaults to matrix.

**Comment by HaiyanLW** [comment]
Agreed.  `stats` and `proxy` all return `dist` object, people may get used to it.

**Comment by koheiw** [comment]
@HaiyanLW, please takeover this branch if you have an idea how it should be like.

**Comment by koheiw** [comment]
Thank you @HaiyanLW for working on the dist and simil. It is better to suppress the warnings in the function? Do users need to see them?

**Comment by kbenoit** [comment]
OK here is what I think we need for the behaviours, with notes in the documentation to make it clear that the return is a distilled object iff no selection is specified.

```r
presDfm <- dfm(corpus_subset(data_corpus_inaugural, Year > 1990), 
               remove = stopwords("english"), stem = TRUE)

# should return dist, upper = FALSE, by default if symmetric
textstat_simil(presDfm, method = "cosine", margin = "documents")
##              1993-Clinton 1997-Clinton 2001-Bush 2005-Bush 2009-Obama 2013-Obama
## 1997-Clinton    0.9252803                                                       
## 2001-Bush       0.9271724    0.9334965                                          
## 2005-Bush       0.9154801    0.9102329 0.9447611                                
## 2009-Obama      0.9015783    0.9399306 0.9255036 0.9004034                      
## 2013-Obama      0.9125611    0.9403480 0.9371368 0.9217499  0.9473229           
## 2017-Trump      0.8963897    0.9227011 0.9364654 0.9213632  0.9137103  0.9177145


# if selection is named, should return a matrix, with the target as columns
textstat_simil(presDfm, method = "cosine", selection = c("2009-Obama", "2017-Trump"), 
               margin = "documents")
##              2009-Obama 2017-Trump
## 2009-Obama    1.0000000  0.9137103
## 2017-Trump    0.9137103  1.0000000
## 1997-Clinton  0.9399306  0.9227011
## 1993-Clinton  0.9015783  0.8963897
## 2001-Bush     0.9255036  0.9364654
## 2005-Bush     0.9004034  0.9213632
## 2013-Obama    0.9473229  0.9177145

# if using selection coerced to a list, it should look like this
as.list(textstat_simil(presDfm, method = "cosine", selection = c("2009-Obama", "2017-Trump"), 
                       margin = "documents"))
## $`2009-Obama`
##   2013-Obama 1997-Clinton    2001-Bush   2017-Trump 1993-Clinton    2005-Bush 
##    0.9473229    0.9399306    0.9255036    0.9137103    0.9015783    0.9004034 
## 
## $`2017-Trump`
##   2001-Bush 1997-Clinton    2005-Bush   2013-Obama   2009-Obama 1993-Clinton 
##   0.9364654    0.9227011    0.9213632    0.9177145    0.9137103    0.8963897 

```

**Comment by HaiyanLW** [comment]
@kbenoit I added `dist.selection` object to handle the situation when `selection` is not NULL, so `as.list` can be applied (otherwise neither `as.list.matrix()` nor `as.list.dist()` is suitable).
```r
> as.list(textstat_dist(presDfm, c("2017-Trump", "2013-Obama"), margin = "documents"))
$`2017-Trump`
 1985-Reagan  1981-Reagan    1989-Bush   2009-Obama 1997-Clinton 1993-Clinton 
   114.82160    109.20165    108.19427     86.01163     79.92496     76.40681 
   2005-Bush   2013-Obama    2001-Bush 
    67.33498     60.22458     54.86347 

$`2013-Obama`
 1985-Reagan    1989-Bush  1981-Reagan   2009-Obama 1997-Clinton 1993-Clinton 
   104.52272    104.20653    103.88455     72.10409     71.86793     70.46276 
   2005-Bush   2017-Trump    2001-Bush 
    66.68583     60.22458     54.69004 
```

**Pull request merged**
