### PR TITLE
Issue 651

### PR DESCRIPTION
**Pull request by koheiw**
Done with #651

### CODE REVIEW

**Comment by kbenoit** [comment]
This is good, but the "terminal" node of a dictionary should just be the (character) vector of keys, no?

So:
```r
dict <- dictionary(one = c("a", "b"), two = c("c", "d"))
dict[[1]]
# Error in validate_dictionary(object) : 
#   Dictionary elements must be named: 
```

**Comment by kbenoit** [comment]
Also should the check for dictionaries not catch the case where there is no name for one of the elements?  e.g.

```r
> testdict <- dictionary(file = "tests/data/dictionaries/laver-garry.cat")
> testdict[[1]]
Dictionary object with 3 key entries.
- CULTURE-HIGH:
  - art, artistic, dance, galler*, museum*, music*, opera*, theatre*
- CULTURE-POPULAR:
  - media
- SPORT:
  - angler*
> testdict
Dictionary object with 9 primary key entries and 2 nested levels.
- CULTURE:
  - CULTURE-HIGH:
    - art, artistic, dance, galler*, museum*, music*, opera*, theatre*
  - CULTURE-POPULAR:
    - media
  - SPORT:
    - angler*
  - people, war_in_iraq, civil_war
```
the last part is not caught by [[1]] but it's there.

**Comment by koheiw** [comment]
There are correct behaviors:
```r
dict <- dictionary(one = c("a", "b"), two = c("c", "d"))

# this works
dict[1]
unclass(dict)[1]

# this does not
dict[[1]]
unclass(dict)[[1] # because there is no names
```
Wordstat dictionaries allow words and sub-categories to coexists side-by-side. In Laver-Garry dictionary, people, war_in_iraq, civil_war are words for CULTURE, but do not appear among the sub-categories without names.
```r
> testdict[['CULTURE']]
Dictionary object with 10 key entries.
- CULTURE-HIGH:
  - art, artistic, dance, galler*, museum*, music*, opera*, theatre*
- CULTURE-POPULAR:
  - media
- SPORT:
  - angler*
```
To make this clear, I change the order of printing:
```r
> testdict['CULTURE']
Dictionary object with 13 key entries.
- CULTURE:
  - people, war_in_iraq, civil_war
  - CULTURE-HIGH:
    - art, artistic, dance, galler*, museum*, music*, opera*, theatre*
  - CULTURE-POPULAR:
    - media
  - SPORT:
    - angler*
```

**Comment by koheiw** [comment]
The decision to make is what to extract with `[` or `[[` (or even `[[[`), because dictionary is a mix of categories and words. In this branch, currently, `[` is to slice root categories, while `[[` is to extract child categories of those. But, `[` can be for child categories, and `[[` be fore all the sibling words:

```r

dict <- dictionary(one = c("a", "b"), 
                   two = list(sub1 = c("c", "d"),
                              sub2 = c("e", "f")))

dict[2]

# Dictionary object with 2 key entries.
# - sub1:
#     - c, d
# - sub2:
#     - e, f

dict[[2]]

# [1] "c" "d" "e" "f"
```

**Comment by koheiw** [comment]
I added `as.list` method for dictionary anyway, so that uses can extract what ever they want.

**Comment by kbenoit** [comment]
OK - I like the current behaviour so let's keep it. I'll merge this PR.

**Pull request merged**
