### PR TITLE
Issue 725

### PR DESCRIPTION
**Pull request by koheiw**
I wrote `dfm_group()` for #725, but it does not do anything about docvars.

### CODE REVIEW

**Comment by kbenoit** [comment]
@koheiw I made a few changes:
* [drastically simplified](https://github.com/kbenoit/quanteda/blob/a4e74095d0ab5a16d078925158a0d4cab31214a4/R/dfm_compress.R#L76-L78) the `dfm_group()` code, so it now just calls `dfm.dfm()`
* made sure that `dfm_compress()` preserves docvars unless the margin of compression is `"documents"` _and_ there are duplicate documents (since no need to compress if there are not).
* implement grouping for dfm in all functions using docvars, the same way that `texts()` works. This does not use the non-standard evaluation as in `ddm_subset()` but it works nicely now with even combinations of variables. (Actually - we should add a test for that!)

This leaves the change you made by adding the internal `group_dfm()` function, which is much neater I agree, but it requires constructing a dfm twice if both margins need compression. I did this earlier in one pass because it's a common use case for compressing on a very large, sparse dfm might happen on both dimensions, so doing it in one pass was faster. How much faster? I am not sure.

**Comment by kbenoit** [comment]
I thought you would not want to live with introducing a possibly less efficient approach 😁 👍 .

**Comment by machinelearner452** [comment]
Hello, new R users so, may be an operator error.  Running the example given 
# dfm_group examples
mycorpus <- corpus(c("a a b", "a b c c", "a c d d", "a c c d"),
docvars = data.frame(grp = c("grp1", "grp1", "grp2", "grp2")))
mydfm <- dfm(mycorpus)
dfm_group(mydfm, groups = "grp")
dfm_group(mydfm, groups = c(1, 1, 2, 2))

yields this error ( even after manaual coping an dpasting the dfm_group function inot the console.):
> dfm_group(mydfm, groups = "grp")
Error in dfm.dfm(x, groups = groups, tolower = FALSE) : 
  groups not equal in length to the number of documents in x
Called from: dfm.dfm(x, groups = groups, tolower = FALSE)
Browse[1]> dfm_group(mydfm, groups = c(1, 1, 2, 2))
Document-feature matrix of: 2 documents, 4 features (25% sparse).
2 x 4 sparse Matrix of class "dfmSparse"
    features
docs a b c d
   1 3 2 2 0
   2 2 0 3 3
Browse[1]> 

Manual entered, > dfm_group <- function(x, groups = NULL) {
+     dfm(x, groups = groups, tolower = FALSE)
+ }
 Did check for updates and no reported errors?  Again a new R user.   
PS thanks for the great function, this is some great work!

**Comment by stefan-mueller** [comment]
Could you type `sessionInfo()` and see which R version and **quanteda** version you are using. You can get the most recent development version by running `devtools::install_github("kbenoit/quanteda")`. 

When I run your example (on MacOS with `quanteda_0.9.9-65`, everything works fine.

```r
mycorpus <- corpus(c("a a b", "a b c c", "a c d d", "a c c d"),
                    docvars = data.frame(grp = c("grp1", "grp1", "grp2", "grp2")))

mydfm <- dfm(mycorpus)

dfm_group(mydfm, groups = "grp")
# Document-feature matrix of: 2 documents, 4 features (25% sparse).
# 2 x 4 sparse Matrix of class "dfmSparse"
#      features
# docs   a b c d
#  grp1 3 2 2 0
#  grp2 2 0 3 3

dfm_group(mydfm, groups = c(1, 1, 2, 2))
# Document-feature matrix of: 2 documents, 4 features (25% sparse).
# 2 x 4 sparse Matrix of class "dfmSparse"
#     features
# docs a b c d
#   1 3 2 2 0
#   2 2 0 3 3
```
Try to replicate this with the latest **quanteda** version – if it still doesn't work, copy the output of `sessionInfo()` and we'll see what could be wrong.

**Comment by machinelearner452** [comment]
Sorry to have trouble you. Reloading the package took care of the issue.

Thanks again for sharing your great work on this package !!

Validation details below.




> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United
States.1252
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C

[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] data.table_1.10.4  shinythemes_1.1.1  shiny_1.0.0        tm_0.7-1

 [5] NLP_0.1-10         tidyr_0.6.1        caTools_1.17.1     readr_1.0.0

 [9] wordcloud_2.5      RColorBrewer_1.1-2 quanteda_0.9.9-50  dplyr_0.5.0


loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9         magrittr_1.5        munsell_0.4.3
 [4] xtable_1.8-2        colorspace_1.3-2    lattice_0.20-34
 [7] R6_2.2.0            fastmatch_1.1-0     plyr_1.8.4
[10] tools_3.3.1         parallel_3.3.1      grid_3.3.1
[13] gtable_0.2.0        DBI_0.5-1           htmltools_0.3.5
[16] digest_0.6.12       lazyeval_0.2.0      RcppParallel_4.3.20
[19] assertthat_0.1      tibble_1.3.0        Matrix_1.2-8
[22] ggplot2_2.2.1       bitops_1.0-6        rsconnect_0.7
[25] mime_0.5            slam_0.1-40         stringi_1.1.5
[28] scales_0.4.1        jsonlite_1.3        httpuv_1.3.3

dfm_group(mydfm, groups = "grp")
Document-feature matrix of: 2 documents, 4 features (25% sparse).
2 x 4 sparse Matrix of class "dfmSparse"
      features
docs   a b c d
  grp1 3 2 2 0
  grp2 2 0 3 3
> dfm_group(mydfm, groups = c(1, 1, 2, 2))
Document-feature matrix of: 2 documents, 4 features (25% sparse).
2 x 4 sparse Matrix of class "dfmSparse"
    features
docs a b c d
   1 3 2 2 0
   2 2 0 3 3
>

**Pull request merged**
