### PR TITLE
Issue 336

### PR DESCRIPTION
**Pull request by koheiw**
Solves #336

### CODE REVIEW

**Comment by koheiw** [comment]
Codecov is complaining about this part of the code in topfeatures.R:
```r
if (is.resampled(x)) {
subdfm <- x[, order(colSums(x[,,1]), decreasing = decreasing), ]
subdfm <- subdfm[, 1:n, ]   # only top n need to be computed        return(data.frame(#features=colnames(subdfm),
            freq=colSums(subdfm[,,1]),
            cilo = apply(colSums(subdfm), 1, stats::quantile, (1 - ci) / 2),
            cihi = apply(colSums(subdfm), 1, stats::quantile, 1 - (1 - ci) / 2)))
}
```
I have never seen resampled dfm objects, and there is actually no `resample()` method for dfm in resample.R. Should I keep or delete this?

**Comment by kbenoit** [comment]
`is.resampled()`  is not currently working, since I never finished it. 

just redefine the function for now (`resample.R`) to return `FALSE` and it should solve the codecov issue.

**Comment by koheiw** [comment]
`topfeatures(x, groups = ...)` is one of the options that proposed, so I am perfectly fine with this.

**Comment by kbenoit** [comment]
cool, please make the change then. Just wrap call dfm_groups first for a new groups argument, then use your code as if by_document = TRUE, and remove by_document from the argument list. Simple = best, and using similar arguments across functions = simpler.

**Pull request merged**
