### PR TITLE
Fix #482 #124

### LINKED ISSUE #482: textmodel_wordfish raises error for large dfm
Hi,

I have a dfm large 22.300x10.047 corpus, for which fitting a wordfish model raises the following error:
```
Error in wordfishcpp(as.matrix(data), as.integer(dir), 1/(priors^2), tol, : std::bad_alloc
3.
stop(structure(list(message = "std::bad_alloc", call = wordfishcpp(as.matrix(data), as.integer(dir), 1/(priors^2), tol, disp, dispersionFloor), cppstack = NULL), .Names = c("message", "call", "cppstack" ), class = c("std::bad_alloc", "C++Error", "error", "condition" ...
2.
wordfishcpp(as.matrix(data), as.integer(dir), 1/(priors^2), tol, disp, dispersionFloor)
1.
textmodel_wordfish(dfm14)
```
I checked the RAM of my PC during the function call and there were over 8GB left right before the error. Is this related to #124? Does wordfish still require a dense matrix?

### PR DESCRIPTION
**Pull request by HaiyanLW**
Use sparse matrix in cpp to handle dfm 
Apply svds() to compute just the top singular vectors
Partially parallelize updating of document/word/dispersion parameters.

### CODE REVIEW

**Comment by kbenoit** [comment]
When the C++ compiles, I am seeing:
```c++
clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../inst/include -DARMA_64BIT_WORD -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/kbenoit/Library/R/3.3/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/RcppParallel/include" -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/RcppArmadillo/include"   -fPIC  -Wall -mtune=core2 -g -O2 -c wordfish_mt.cpp -o wordfish_mt.o
wordfish_mt.cpp:75:35: warning: field 'beta' will be initialized after field 'theta' [-Wreorder]
        : alpha(alpha), psi(psi), beta(beta), theta(theta), phi(phi), wfm(wfm), tolvec(tolvec), 
                                  ^
wordfish_mt.cpp:129:35: warning: field 'beta' will be initialized after field 'theta' [-Wreorder]
        : alpha(alpha), psi(psi), beta(beta), theta(theta), phi(phi), wfm(wfm), tolvec(tolvec), 
                                  ^
2 warnings generated.
```

**Comment by kbenoit** [comment]
And from Windows:

```c++
c:/Rtools/mingw_64/bin/g++  -std=c++0x -I"C:/PROGRA~1/R/R-33~1.2/include" -DNDEBUG -I../inst/include -DARMA_64BIT_WORD   -I"C:/Users/kbenoit/Documents/R/win-library/3.3/Rcpp/include" -I"C:/Users/kbenoit/Documents/R/win-library/3.3/RcppParallel/include" -I"C:/Users/kbenoit/Documents/R/win-library/3.3/RcppArmadillo/include" -I"d:/Compiler/gcc-4.9.3/local330/include"  -DRCPP_PARALLEL_USE_TBB=1   -O2 -Wall  -mtune=core2 -c wordfish_mt.cpp -o wordfish_mt.o
wordfish_mt.cpp: In constructor 'WordPar::WordPar(const colvec&, Rcpp::NumericVector&, Rcpp::NumericVector&, const colvec&, const rowvec&, const sp_mat&, const NumericVector&, int, double, double, double)':
wordfish_mt.cpp:62:21: warning: 'WordPar::beta' will be initialized after [-Wreorder]
     RVector<double> beta; 
                     ^
wordfish_mt.cpp:60:25: warning:   'const colvec& WordPar::theta' [-Wreorder]
     const arma::colvec& theta; 
                         ^
wordfish_mt.cpp:71:5: warning:   when initialized here [-Wreorder]
     WordPar(const arma::colvec& alpha,  NumericVector& psi,  NumericVector& beta, 
     ^
wordfish_mt.cpp: In constructor 'DocPar::DocPar(Rcpp::NumericVector&, const rowvec&, const rowvec&, Rcpp::NumericVector&, const rowvec&, const sp_mat&, const NumericVector&, int, double, double, double)':
wordfish_mt.cpp:116:25: warning: 'DocPar::beta' will be initialized after [-Wreorder]
     const arma::rowvec& beta; 
                         ^
wordfish_mt.cpp:114:21: warning:   'RcppParallel::RVector<double> DocPar::theta' [-Wreorder]
     RVector<double> theta; 
                     ^
wordfish_mt.cpp:125:5: warning:   when initialized here [-Wreorder]
     DocPar(NumericVector& alpha,  const arma::rowvec& psi,  const arma::rowvec& beta, 
 
```    ^

**Comment by kbenoit** [comment]
For some reason, once I've built the package and reinstalled, this crashes my R session (aborts RStudio) on macOS Sierra 10.12.3:

```r
ie2010dfm <- dfm(data_corpus_irishbudget2010, verbose = FALSE)
(wfm1 <- textmodel_wordfish(ie2010dfm, dir = c(6,5)))
```

**Comment by HaiyanLW** [comment]
The warnings are due the order of the parameters, I'll correct it.

**Comment by kbenoit** [comment]
```r
> rbenchmark::benchmark(textmodel_wordfish(data = dfm(data_corpus_inaugural), version = "parallel"), textmodel_wordfish(data = dfm(data_corpus_inaugural), version = "serial"), replications = 1)
svd done
svd done
                                                                         test replications elapsed relative user.self sys.self user.child sys.child
1 textmodel_wordfish(data = dfm(data_corpus_inaugural), version = "parallel")            1  55.328    4.262    51.325    3.824          0         0
2   textmodel_wordfish(data = dfm(data_corpus_inaugural), version = "serial")            1  12.982    1.000    12.685    0.251          0         0
```

**Comment by HaiyanLW** [comment]
svds() is designed to work with sparse matrix and it seems has a better performance when the residual matrix is of a reasonable sparsity. 
```r
> rbenchmark::benchmark(textmodel_wordfish(data = dfm(data_corpus_inaugural), version = "parallel", residual_floor = 0.2), textmodel_wordfish(data = dfm(data_corpus_inaugural), version = "serial"), replications = 1)
svd done
svd done
                                                                                               test replications elapsed
1 textmodel_wordfish(data = dfm(data_corpus_inaugural), version = "parallel", residual_floor = 0.2)            1   16.59
2                         textmodel_wordfish(data = dfm(data_corpus_inaugural), version = "serial")            1   19.86
  relative user.self sys.self user.child sys.child
1    1.000     16.42     0.26         NA        NA
2    1.197     19.49     0.14         NA        NA```

**Comment by HaiyanLW** [comment]
```r
> rbenchmark::benchmark(textmodel_wordfish(data = dfm(data_corpus_inaugural), version = "parallel", residual_floor = 0.5), textmodel_wordfish(data = dfm(data_corpus_inaugural), version = "serial"), replications = 1)
svd done
svd done
                                                                                               test
1 textmodel_wordfish(data = dfm(data_corpus_inaugural), version = "parallel", residual_floor = 0.5)
2                         textmodel_wordfish(data = dfm(data_corpus_inaugural), version = "serial")
  replications elapsed relative user.self sys.self user.child sys.child
1            1    3.08     1.00      7.83     0.00         NA        NA
2            1   19.25     6.25     19.06     0.15         NA        NA```

**Pull request closed without merging**
